log_dir: "Checkpoint"
mixed_precision: "fp16"
data_folder: "wikipedia_20231101.ar.processed"
batch_size: 192
save_interval: 5000
log_interval: 10
num_process: 1 # number of GPUs
num_steps: 1000000

dataset_params:
    tokenizer: "aubmindlab/bert-base-arabertv2"
    token_separator: "P" # token used for phoneme separator (space)
    token_mask: "M" # token used for phoneme mask
    word_separator: 87 # token used for word separator (W)
    
    max_mel_length: 512 # max phoneme length
    
    word_mask_prob: 0.15 # probability to select work for prediction
    phoneme_mask_prob: 0.8 # probability to mask phonemes
    replace_prob: 0.1 # probablity to replace phonemes
    
model_params:
    vocab_size: 178
    hidden_size: 768
    num_attention_heads: 12
    intermediate_size: 2048
    max_position_embeddings: 512
    num_hidden_layers: 12
    dropout: 0.1